"""implement intelligence and enterprise integrations

Revision ID: 1991d01a0910
Revises: 1efcbcbb81f4
Create Date: 2026-08-19 16:40:50.256706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1991d01a0910'
down_revision: Union[str, Sequence[str], None] = '1efcbcbb81f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('integration_type', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_integrations_id'), 'organization_integrations', ['id'], unique=False)
    op.create_index(op.f('ix_organization_integrations_organization_id'), 'organization_integrations', ['organization_id'], unique=False)
    op.create_table('integration_sync_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('records_created', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('error_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['integration_id'], ['organization_integrations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_sync_jobs_id'), 'integration_sync_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_integration_sync_jobs_idempotency_key'), 'integration_sync_jobs', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_integration_sync_jobs_integration_id'), 'integration_sync_jobs', ['integration_id'], unique=False)
    op.create_index(op.f('ix_integration_sync_jobs_organization_id'), 'integration_sync_jobs', ['organization_id'], unique=False)
    op.create_table('student_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('signal_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_signals_id'), 'student_signals', ['id'], unique=False)
    op.create_index(op.f('ix_student_signals_organization_id'), 'student_signals', ['organization_id'], unique=False)
    op.create_index(op.f('ix_student_signals_severity'), 'student_signals', ['severity'], unique=False)
    op.create_index(op.f('ix_student_signals_signal_type'), 'student_signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_student_signals_status'), 'student_signals', ['status'], unique=False)
    op.create_index(op.f('ix_student_signals_student_id'), 'student_signals', ['student_id'], unique=False)
    op.create_table('student_interventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('counselor_id', sa.Integer(), nullable=True),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('intervention_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['counselor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signal_id'], ['student_signals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_interventions_counselor_id'), 'student_interventions', ['counselor_id'], unique=False)
    op.create_index(op.f('ix_student_interventions_id'), 'student_interventions', ['id'], unique=False)
    op.create_index(op.f('ix_student_interventions_organization_id'), 'student_interventions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_student_interventions_status'), 'student_interventions', ['status'], unique=False)
    op.create_index(op.f('ix_student_interventions_student_id'), 'student_interventions', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_interventions_student_id'), table_name='student_interventions')
    op.drop_index(op.f('ix_student_interventions_status'), table_name='student_interventions')
    op.drop_index(op.f('ix_student_interventions_organization_id'), table_name='student_interventions')
    op.drop_index(op.f('ix_student_interventions_id'), table_name='student_interventions')
    op.drop_index(op.f('ix_student_interventions_counselor_id'), table_name='student_interventions')
    op.drop_table('student_interventions')
    op.drop_index(op.f('ix_student_signals_student_id'), table_name='student_signals')
    op.drop_index(op.f('ix_student_signals_status'), table_name='student_signals')
    op.drop_index(op.f('ix_student_signals_signal_type'), table_name='student_signals')
    op.drop_index(op.f('ix_student_signals_severity'), table_name='student_signals')
    op.drop_index(op.f('ix_student_signals_organization_id'), table_name='student_signals')
    op.drop_index(op.f('ix_student_signals_id'), table_name='student_signals')
    op.drop_table('student_signals')
    op.drop_index(op.f('ix_integration_sync_jobs_organization_id'), table_name='integration_sync_jobs')
    op.drop_index(op.f('ix_integration_sync_jobs_integration_id'), table_name='integration_sync_jobs')
    op.drop_index(op.f('ix_integration_sync_jobs_idempotency_key'), table_name='integration_sync_jobs')
    op.drop_index(op.f('ix_integration_sync_jobs_id'), table_name='integration_sync_jobs')
    op.drop_table('integration_sync_jobs')
    op.drop_index(op.f('ix_organization_integrations_organization_id'), table_name='organization_integrations')
    op.drop_index(op.f('ix_organization_integrations_id'), table_name='organization_integrations')
    op.drop_table('organization_integrations')
    # ### end Alembic commands ###
