"""update certificates schema

Revision ID: 2c34d0f81916
Revises: 53f6ca26bed6
Create Date: 2026-08-19 14:44:56.096329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c34d0f81916'
down_revision: Union[str, Sequence[str], None] = '53f6ca26bed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('certificates', sa.Column('organization', sa.String(length=255), nullable=False))
    op.add_column('certificates', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('certificates', sa.Column('file_url', sa.String(length=1000), nullable=True))
    op.drop_column('certificates', 'name')
    op.drop_column('certificates', 'credential_id')
    op.drop_column('certificates', 'issuer')
    op.drop_column('certificates', 'url')
    op.drop_column('certificates', 'expiry_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('expiry_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('certificates', sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('certificates', sa.Column('issuer', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('certificates', sa.Column('credential_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('certificates', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('certificates', 'file_url')
    op.drop_column('certificates', 'category')
    op.drop_column('certificates', 'organization')
    op.drop_column('certificates', 'title')
    # ### end Alembic commands ###
