"""add_remaining_tables_phase_final

Revision ID: 425c990b5e2c
Revises: c72a8f851442
Create Date: 2026-08-19 17:54:05.781985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '425c990b5e2c'
down_revision: Union[str, Sequence[str], None] = 'c72a8f851442'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_student_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_career_dna_snapshots_career_dna_id'), table_name='career_dna_snapshots')
    op.drop_index(op.f('ix_career_dna_snapshots_id'), table_name='career_dna_snapshots')
    op.drop_index(op.f('ix_career_dna_snapshots_student_id'), table_name='career_dna_snapshots')
    op.drop_table('career_dna_snapshots')
    op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_student_signals_id'), table_name='student_signals')
    op.drop_index(op.f('ix_student_signals_organization_id'), table_name='student_signals')
    op.drop_index(op.f('ix_student_signals_severity'), table_name='student_signals')
    op.drop_index(op.f('ix_student_signals_signal_type'), table_name='student_signals')
    op.drop_index(op.f('ix_student_signals_status'), table_name='student_signals')
    op.drop_index(op.f('ix_student_signals_student_id'), table_name='student_signals')
    op.drop_table('student_signals')
    op.drop_index(op.f('ix_career_dna_id'), table_name='career_dna')
    op.drop_index(op.f('ix_career_dna_student_id'), table_name='career_dna')
    op.drop_table('career_dna')
    op.drop_index(op.f('ix_student_interventions_counselor_id'), table_name='student_interventions')
    op.drop_index(op.f('ix_student_interventions_id'), table_name='student_interventions')
    op.drop_index(op.f('ix_student_interventions_organization_id'), table_name='student_interventions')
    op.drop_index(op.f('ix_student_interventions_status'), table_name='student_interventions')
    op.drop_index(op.f('ix_student_interventions_student_id'), table_name='student_interventions')
    op.drop_table('student_interventions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_interventions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('counselor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('signal_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('intervention_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('due_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['counselor_id'], ['users.id'], name=op.f('student_interventions_counselor_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('student_interventions_organization_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signal_id'], ['student_signals.id'], name=op.f('student_interventions_signal_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('student_interventions_student_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('student_interventions_pkey'))
    )
    op.create_index(op.f('ix_student_interventions_student_id'), 'student_interventions', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_interventions_status'), 'student_interventions', ['status'], unique=False)
    op.create_index(op.f('ix_student_interventions_organization_id'), 'student_interventions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_student_interventions_id'), 'student_interventions', ['id'], unique=False)
    op.create_index(op.f('ix_student_interventions_counselor_id'), 'student_interventions', ['counselor_id'], unique=False)
    op.create_table('career_dna',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('interests', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('aspirations', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('work_style', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('learning_style', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('career_zones', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('career_dna_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('career_dna_pkey'))
    )
    op.create_index(op.f('ix_career_dna_student_id'), 'career_dna', ['student_id'], unique=True)
    op.create_index(op.f('ix_career_dna_id'), 'career_dna', ['id'], unique=False)
    op.create_table('student_signals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('signal_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('detected_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('student_signals_organization_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('student_signals_student_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('student_signals_pkey'))
    )
    op.create_index(op.f('ix_student_signals_student_id'), 'student_signals', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_signals_status'), 'student_signals', ['status'], unique=False)
    op.create_index(op.f('ix_student_signals_signal_type'), 'student_signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_student_signals_severity'), 'student_signals', ['severity'], unique=False)
    op.create_index(op.f('ix_student_signals_organization_id'), 'student_signals', ['organization_id'], unique=False)
    op.create_index(op.f('ix_student_signals_id'), 'student_signals', ['id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('conversation_messages_conversation_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('conversation_messages_pkey'))
    )
    op.create_index(op.f('ix_conversation_messages_id'), 'conversation_messages', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    op.create_table('career_dna_snapshots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('career_dna_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('grade', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('academic_year', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('snapshot_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('change_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['career_dna_id'], ['career_dna.id'], name=op.f('career_dna_snapshots_career_dna_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('career_dna_snapshots_student_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('career_dna_snapshots_pkey'))
    )
    op.create_index(op.f('ix_career_dna_snapshots_student_id'), 'career_dna_snapshots', ['student_id'], unique=False)
    op.create_index(op.f('ix_career_dna_snapshots_id'), 'career_dna_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_career_dna_snapshots_career_dna_id'), 'career_dna_snapshots', ['career_dna_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('context_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('conversations_student_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('conversations_pkey'))
    )
    op.create_index(op.f('ix_conversations_student_id'), 'conversations', ['student_id'], unique=False)
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    # ### end Alembic commands ###
