"""create career passport

Revision ID: 4e1c1692a2ac
Revises: 335c336f7ce9
Create Date: 2026-08-19 15:15:41.393869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e1c1692a2ac'
down_revision: Union[str, Sequence[str], None] = '335c336f7ce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_passports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('interests', sa.Text(), nullable=True),
    sa.Column('work_style', sa.Text(), nullable=True),
    sa.Column('learning_style', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_passports_id'), 'career_passports', ['id'], unique=False)
    op.create_index(op.f('ix_career_passports_student_id'), 'career_passports', ['student_id'], unique=True)
    op.drop_index(op.f('ix_passports_id'), table_name='passports')
    op.drop_index(op.f('ix_passports_student_id'), table_name='passports')
    op.drop_table('passports')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('about', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('skills', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('work_style', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('learning_style', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('passports_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('passports_pkey'))
    )
    op.create_index(op.f('ix_passports_student_id'), 'passports', ['student_id'], unique=True)
    op.create_index(op.f('ix_passports_id'), 'passports', ['id'], unique=False)
    op.drop_index(op.f('ix_career_passports_student_id'), table_name='career_passports')
    op.drop_index(op.f('ix_career_passports_id'), table_name='career_passports')
    op.drop_table('career_passports')
    # ### end Alembic commands ###
