"""update projects schema

Revision ID: 53f6ca26bed6
Revises: bc22309480e4
Create Date: 2026-08-19 14:33:12.216454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53f6ca26bed6'
down_revision: Union[str, Sequence[str], None] = 'bc22309480e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('skills', sa.String(length=2000), nullable=True))
    op.add_column('projects', sa.Column('outcome', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('evidence', sa.String(length=1000), nullable=True))
    op.alter_column('projects', 'role',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_column('projects', 'end_date')
    op.drop_column('projects', 'start_date')
    op.drop_column('projects', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('projects', 'role',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('projects', 'evidence')
    op.drop_column('projects', 'outcome')
    op.drop_column('projects', 'skills')
    # ### end Alembic commands ###
