"""core explorers database schema

Revision ID: 56e302466531
Revises: 4e1c1692a2ac
Create Date: 2026-08-19 15:21:17.621428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56e302466531'
down_revision: Union[str, Sequence[str], None] = '4e1c1692a2ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_categories_id'), 'career_categories', ['id'], unique=False)
    op.create_index(op.f('ix_career_categories_slug'), 'career_categories', ['slug'], unique=True)
    op.create_table('careers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('education_level', sa.String(length=255), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), nullable=True),
    sa.Column('demand_level', sa.String(length=50), nullable=True),
    sa.Column('future_demand', sa.String(length=50), nullable=True),
    sa.Column('work_environment', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_careers_id'), 'careers', ['id'], unique=False)
    op.create_index(op.f('ix_careers_slug'), 'careers', ['slug'], unique=True)
    op.create_table('universities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('ranking', sa.Integer(), nullable=True),
    sa.Column('acceptance_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tuition_min', sa.Integer(), nullable=True),
    sa.Column('tuition_max', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_universities_id'), 'universities', ['id'], unique=False)
    op.create_index(op.f('ix_universities_slug'), 'universities', ['slug'], unique=True)
    op.create_table('career_category_link',
    sa.Column('career_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['career_categories.id'], ),
    sa.PrimaryKeyConstraint('career_id', 'category_id')
    )
    op.create_table('career_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('career_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('importance', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_skills_career_id'), 'career_skills', ['career_id'], unique=False)
    op.create_index(op.f('ix_career_skills_id'), 'career_skills', ['id'], unique=False)
    op.create_table('career_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('career_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('importance', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_subjects_career_id'), 'career_subjects', ['career_id'], unique=False)
    op.create_index(op.f('ix_career_subjects_id'), 'career_subjects', ['id'], unique=False)
    op.create_table('university_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('degree_type', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entry_requirements', sa.Text(), nullable=True),
    sa.Column('tuition', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_university_courses_id'), 'university_courses', ['id'], unique=False)
    op.create_index(op.f('ix_university_courses_university_id'), 'university_courses', ['university_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_university_courses_university_id'), table_name='university_courses')
    op.drop_index(op.f('ix_university_courses_id'), table_name='university_courses')
    op.drop_table('university_courses')
    op.drop_index(op.f('ix_career_subjects_id'), table_name='career_subjects')
    op.drop_index(op.f('ix_career_subjects_career_id'), table_name='career_subjects')
    op.drop_table('career_subjects')
    op.drop_index(op.f('ix_career_skills_id'), table_name='career_skills')
    op.drop_index(op.f('ix_career_skills_career_id'), table_name='career_skills')
    op.drop_table('career_skills')
    op.drop_table('career_category_link')
    op.drop_index(op.f('ix_universities_slug'), table_name='universities')
    op.drop_index(op.f('ix_universities_id'), table_name='universities')
    op.drop_table('universities')
    op.drop_index(op.f('ix_careers_slug'), table_name='careers')
    op.drop_index(op.f('ix_careers_id'), table_name='careers')
    op.drop_table('careers')
    op.drop_index(op.f('ix_career_categories_slug'), table_name='career_categories')
    op.drop_index(op.f('ix_career_categories_id'), table_name='career_categories')
    op.drop_table('career_categories')
    # ### end Alembic commands ###
