"""add missing modules

Revision ID: 60d58736cdc7
Revises: 56e302466531
Create Date: 2026-08-19 15:25:04.417292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60d58736cdc7'
down_revision: Union[str, Sequence[str], None] = '56e302466531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_student_id'), 'notifications', ['student_id'], unique=False)
    op.create_table('weekly_checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('accomplishments', sa.Text(), nullable=True),
    sa.Column('learnings', sa.Text(), nullable=True),
    sa.Column('difficulties', sa.Text(), nullable=True),
    sa.Column('proud_of', sa.Text(), nullable=True),
    sa.Column('improvement_area', sa.Text(), nullable=True),
    sa.Column('mood', sa.String(length=50), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_checkins_id'), 'weekly_checkins', ['id'], unique=False)
    op.create_index(op.f('ix_weekly_checkins_student_id'), 'weekly_checkins', ['student_id'], unique=False)
    op.create_table('career_dna_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('career_dna_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('academic_year', sa.String(length=50), nullable=True),
    sa.Column('snapshot_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['career_dna_id'], ['career_dna.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_dna_snapshots_career_dna_id'), 'career_dna_snapshots', ['career_dna_id'], unique=False)
    op.create_index(op.f('ix_career_dna_snapshots_id'), 'career_dna_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_career_dna_snapshots_student_id'), 'career_dna_snapshots', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_career_dna_snapshots_student_id'), table_name='career_dna_snapshots')
    op.drop_index(op.f('ix_career_dna_snapshots_id'), table_name='career_dna_snapshots')
    op.drop_index(op.f('ix_career_dna_snapshots_career_dna_id'), table_name='career_dna_snapshots')
    op.drop_table('career_dna_snapshots')
    op.drop_index(op.f('ix_weekly_checkins_student_id'), table_name='weekly_checkins')
    op.drop_index(op.f('ix_weekly_checkins_id'), table_name='weekly_checkins')
    op.drop_table('weekly_checkins')
    op.drop_index(op.f('ix_notifications_student_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
