"""create milestones table

Revision ID: 660d2383a117
Revises: 82a7d4a7634c
Create Date: 2026-08-19 02:56:47.189807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '660d2383a117'
down_revision: Union[str, Sequence[str], None] = '82a7d4a7634c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milestones_id'), 'milestones', ['id'], unique=False)
    op.create_index(op.f('ix_milestones_roadmap_id'), 'milestones', ['roadmap_id'], unique=False)
    # Drop tasks FK before dropping roadmap_milestones to avoid dependency error
    op.drop_constraint(op.f('tasks_milestone_id_fkey'), 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_roadmap_milestones_id'), table_name='roadmap_milestones')
    op.drop_index(op.f('ix_roadmap_milestones_roadmap_id'), table_name='roadmap_milestones')
    op.drop_table('roadmap_milestones')
    op.create_foreign_key(None, 'tasks', 'milestones', ['milestone_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_milestone_id_fkey'), 'tasks', 'roadmap_milestones', ['milestone_id'], ['id'])
    op.create_table('roadmap_milestones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('roadmap_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('grade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], name=op.f('roadmap_milestones_roadmap_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('roadmap_milestones_pkey'))
    )
    op.create_index(op.f('ix_roadmap_milestones_roadmap_id'), 'roadmap_milestones', ['roadmap_id'], unique=False)
    op.create_index(op.f('ix_roadmap_milestones_id'), 'roadmap_milestones', ['id'], unique=False)
    op.drop_index(op.f('ix_milestones_roadmap_id'), table_name='milestones')
    op.drop_index(op.f('ix_milestones_id'), table_name='milestones')
    op.drop_table('milestones')
    # ### end Alembic commands ###
