"""add roadmap hierarchy models

Revision ID: 6e3e6d2bebb8
Revises: 60d58736cdc7
Create Date: 2026-08-19 16:05:02.477654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e3e6d2bebb8'
down_revision: Union[str, Sequence[str], None] = '60d58736cdc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmap_year_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(length=50), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('academic_objectives', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('career_objectives', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('university_objectives', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('personal_objectives', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_year_plans_id'), 'roadmap_year_plans', ['id'], unique=False)
    op.create_index(op.f('ix_roadmap_year_plans_roadmap_id'), 'roadmap_year_plans', ['roadmap_id'], unique=False)
    op.create_index(op.f('ix_roadmap_year_plans_student_id'), 'roadmap_year_plans', ['student_id'], unique=False)
    op.create_table('roadmap_monthly_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year_plan_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('objectives', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['year_plan_id'], ['roadmap_year_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_monthly_plans_id'), 'roadmap_monthly_plans', ['id'], unique=False)
    op.create_index(op.f('ix_roadmap_monthly_plans_student_id'), 'roadmap_monthly_plans', ['student_id'], unique=False)
    op.create_index(op.f('ix_roadmap_monthly_plans_year_plan_id'), 'roadmap_monthly_plans', ['year_plan_id'], unique=False)
    op.create_table('roadmap_weekly_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monthly_plan_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('objectives', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['monthly_plan_id'], ['roadmap_monthly_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_weekly_plans_id'), 'roadmap_weekly_plans', ['id'], unique=False)
    op.create_index(op.f('ix_roadmap_weekly_plans_monthly_plan_id'), 'roadmap_weekly_plans', ['monthly_plan_id'], unique=False)
    op.create_index(op.f('ix_roadmap_weekly_plans_student_id'), 'roadmap_weekly_plans', ['student_id'], unique=False)
    op.add_column('tasks', sa.Column('year_plan_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('monthly_plan_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('weekly_plan_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tasks_monthly_plan_id'), 'tasks', ['monthly_plan_id'], unique=False)
    op.create_index(op.f('ix_tasks_weekly_plan_id'), 'tasks', ['weekly_plan_id'], unique=False)
    op.create_index(op.f('ix_tasks_year_plan_id'), 'tasks', ['year_plan_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'roadmap_year_plans', ['year_plan_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'roadmap_monthly_plans', ['monthly_plan_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'roadmap_weekly_plans', ['weekly_plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_year_plan_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_weekly_plan_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_monthly_plan_id'), table_name='tasks')
    op.drop_column('tasks', 'weekly_plan_id')
    op.drop_column('tasks', 'monthly_plan_id')
    op.drop_column('tasks', 'year_plan_id')
    op.drop_index(op.f('ix_roadmap_weekly_plans_student_id'), table_name='roadmap_weekly_plans')
    op.drop_index(op.f('ix_roadmap_weekly_plans_monthly_plan_id'), table_name='roadmap_weekly_plans')
    op.drop_index(op.f('ix_roadmap_weekly_plans_id'), table_name='roadmap_weekly_plans')
    op.drop_table('roadmap_weekly_plans')
    op.drop_index(op.f('ix_roadmap_monthly_plans_year_plan_id'), table_name='roadmap_monthly_plans')
    op.drop_index(op.f('ix_roadmap_monthly_plans_student_id'), table_name='roadmap_monthly_plans')
    op.drop_index(op.f('ix_roadmap_monthly_plans_id'), table_name='roadmap_monthly_plans')
    op.drop_table('roadmap_monthly_plans')
    op.drop_index(op.f('ix_roadmap_year_plans_student_id'), table_name='roadmap_year_plans')
    op.drop_index(op.f('ix_roadmap_year_plans_roadmap_id'), table_name='roadmap_year_plans')
    op.drop_index(op.f('ix_roadmap_year_plans_id'), table_name='roadmap_year_plans')
    op.drop_table('roadmap_year_plans')
    # ### end Alembic commands ###
