"""update task model for denormalization

Revision ID: 7478c2d0f2f4
Revises: 2c34d0f81916
Create Date: 2026-08-19 14:51:20.289782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7478c2d0f2f4'
down_revision: Union[str, Sequence[str], None] = '2c34d0f81916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('student_id', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('roadmap_id', sa.Integer(), nullable=True))
    op.alter_column('tasks', 'milestone_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_tasks_roadmap_id'), 'tasks', ['roadmap_id'], unique=False)
    op.create_index(op.f('ix_tasks_student_id'), 'tasks', ['student_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'students', ['student_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'roadmaps', ['roadmap_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_student_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_roadmap_id'), table_name='tasks')
    op.alter_column('tasks', 'milestone_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('tasks', 'roadmap_id')
    op.drop_column('tasks', 'student_id')
    # ### end Alembic commands ###
