"""create career dna

Revision ID: 82a7d4a7634c
Revises: dfca0423ffae
Create Date: 2026-08-19 02:49:37.692163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82a7d4a7634c'
down_revision: Union[str, Sequence[str], None] = 'dfca0423ffae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_dna',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('interests', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('aspirations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('work_style', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('learning_style', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('career_zones', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_dna_id'), 'career_dna', ['id'], unique=False)
    op.create_index(op.f('ix_career_dna_student_id'), 'career_dna', ['student_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_career_dna_student_id'), table_name='career_dna')
    op.drop_index(op.f('ix_career_dna_id'), table_name='career_dna')
    op.drop_table('career_dna')
    # ### end Alembic commands ###
