"""add auth0_id to users

Revision ID: 83233e950c45
Revises: b95059cac1e0
Create Date: 2026-08-18 17:31:01.291191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83233e950c45'
down_revision: Union[str, Sequence[str], None] = 'b95059cac1e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth0_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_auth0_id'), 'users', ['auth0_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_auth0_id'), table_name='users')
    op.drop_column('users', 'auth0_id')
    # ### end Alembic commands ###
