"""rename to roadmap milestones

Revision ID: a503e7eb99a1
Revises: 526153c08119
Create Date: 2026-08-19 02:41:20.417002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a503e7eb99a1'
down_revision: Union[str, Sequence[str], None] = '526153c08119'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmap_milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_milestones_id'), 'roadmap_milestones', ['id'], unique=False)
    op.create_index(op.f('ix_roadmap_milestones_roadmap_id'), 'roadmap_milestones', ['roadmap_id'], unique=False)
    op.drop_index(op.f('ix_roadmap_items_id'), table_name='roadmap_items')
    op.drop_index(op.f('ix_roadmap_items_roadmap_id'), table_name='roadmap_items')
    op.drop_table('roadmap_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmap_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('roadmap_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('grade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], name=op.f('roadmap_items_roadmap_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('roadmap_items_pkey'))
    )
    op.create_index(op.f('ix_roadmap_items_roadmap_id'), 'roadmap_items', ['roadmap_id'], unique=False)
    op.create_index(op.f('ix_roadmap_items_id'), 'roadmap_items', ['id'], unique=False)
    op.drop_index(op.f('ix_roadmap_milestones_roadmap_id'), table_name='roadmap_milestones')
    op.drop_index(op.f('ix_roadmap_milestones_id'), table_name='roadmap_milestones')
    op.drop_table('roadmap_milestones')
    # ### end Alembic commands ###
