"""update achievements schema

Revision ID: bc22309480e4
Revises: 188bbb698f64
Create Date: 2026-08-19 12:58:50.834907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc22309480e4'
down_revision: Union[str, Sequence[str], None] = '188bbb698f64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievements', sa.Column('organization', sa.String(length=255), nullable=True))
    op.add_column('achievements', sa.Column('achievement_date', sa.DateTime(), nullable=True))
    op.add_column('achievements', sa.Column('skills', sa.String(length=2000), nullable=True))
    op.alter_column('achievements', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('achievements', 'date_achieved')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievements', sa.Column('date_achieved', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('achievements', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('achievements', 'skills')
    op.drop_column('achievements', 'achievement_date')
    op.drop_column('achievements', 'organization')
    # ### end Alembic commands ###
