"""add phase A models

Revision ID: c72a8f851442
Revises: 1991d01a0910
Create Date: 2026-08-19 17:02:52.657576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c72a8f851442'
down_revision: Union[str, Sequence[str], None] = '1991d01a0910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('opportunity_type', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('eligibility', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('interests', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_id'), 'opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_opportunities_organization_id'), 'opportunities', ['organization_id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=True),
    sa.Column('program_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('target_term', sa.String(length=50), nullable=True),
    sa.Column('application_type', sa.String(length=100), nullable=True),
    sa.Column('application_deadline', sa.Date(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_index(op.f('ix_applications_student_id'), 'applications', ['student_id'], unique=False)
    op.create_index(op.f('ix_applications_university_id'), 'applications', ['university_id'], unique=False)
    op.create_table('student_opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_opportunities_id'), 'student_opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_student_opportunities_opportunity_id'), 'student_opportunities', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_student_opportunities_student_id'), 'student_opportunities', ['student_id'], unique=False)
    op.create_table('student_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('outcome_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('achieved_at', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('metadata_dict', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_outcomes_id'), 'student_outcomes', ['id'], unique=False)
    op.create_index(op.f('ix_student_outcomes_student_id'), 'student_outcomes', ['student_id'], unique=False)
    op.create_table('student_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_skills_id'), 'student_skills', ['id'], unique=False)
    op.create_index(op.f('ix_student_skills_skill_id'), 'student_skills', ['skill_id'], unique=False)
    op.create_index(op.f('ix_student_skills_student_id'), 'student_skills', ['student_id'], unique=False)
    op.create_table('application_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_requirements_application_id'), 'application_requirements', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_requirements_id'), 'application_requirements', ['id'], unique=False)
    op.create_table('roadmap_weekly_plan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weekly_plan_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['weekly_plan_id'], ['roadmap_weekly_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_weekly_plan_items_id'), 'roadmap_weekly_plan_items', ['id'], unique=False)
    op.create_index(op.f('ix_roadmap_weekly_plan_items_weekly_plan_id'), 'roadmap_weekly_plan_items', ['weekly_plan_id'], unique=False)
    op.add_column('roadmap_weekly_plans', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.add_column('roadmap_weekly_plans', sa.Column('generated_by', sa.String(length=50), nullable=True))
    op.alter_column('roadmap_weekly_plans', 'monthly_plan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_roadmap_weekly_plans_organization_id'), 'roadmap_weekly_plans', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'roadmap_weekly_plans', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roadmap_weekly_plans', type_='foreignkey')
    op.drop_index(op.f('ix_roadmap_weekly_plans_organization_id'), table_name='roadmap_weekly_plans')
    op.alter_column('roadmap_weekly_plans', 'monthly_plan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('roadmap_weekly_plans', 'generated_by')
    op.drop_column('roadmap_weekly_plans', 'organization_id')
    op.drop_index(op.f('ix_roadmap_weekly_plan_items_weekly_plan_id'), table_name='roadmap_weekly_plan_items')
    op.drop_index(op.f('ix_roadmap_weekly_plan_items_id'), table_name='roadmap_weekly_plan_items')
    op.drop_table('roadmap_weekly_plan_items')
    op.drop_index(op.f('ix_application_requirements_id'), table_name='application_requirements')
    op.drop_index(op.f('ix_application_requirements_application_id'), table_name='application_requirements')
    op.drop_table('application_requirements')
    op.drop_index(op.f('ix_student_skills_student_id'), table_name='student_skills')
    op.drop_index(op.f('ix_student_skills_skill_id'), table_name='student_skills')
    op.drop_index(op.f('ix_student_skills_id'), table_name='student_skills')
    op.drop_table('student_skills')
    op.drop_index(op.f('ix_student_outcomes_student_id'), table_name='student_outcomes')
    op.drop_index(op.f('ix_student_outcomes_id'), table_name='student_outcomes')
    op.drop_table('student_outcomes')
    op.drop_index(op.f('ix_student_opportunities_student_id'), table_name='student_opportunities')
    op.drop_index(op.f('ix_student_opportunities_opportunity_id'), table_name='student_opportunities')
    op.drop_index(op.f('ix_student_opportunities_id'), table_name='student_opportunities')
    op.drop_table('student_opportunities')
    op.drop_index(op.f('ix_applications_university_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_student_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_opportunities_organization_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
